FROM python:3.9-slim

RUN apt-get update && apt-get install -y ffmpeg && \
    pip install --no-cache-dir numpy soundfile && \
    apt-get clean

COPY preprocess.py /preprocess.py

ENTRYPOINT ["python", "/preprocess.py"]
