version: '3.1'

services:
  mysql:
    image: mysql:8
    container_name: mysql-asr
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: asr_db
      MYSQL_USER: asr_user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
