# Dockerfile.inference
FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libsndfile1 && \
    pip install --no-cache-dir tensorflow librosa numpy soundfile && \
    apt-get clean

COPY inference.py .

ENTRYPOINT ["python", "inference.py"]
